name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Checkout
      uses: actions/checkout@master
    - name: Build mod jar
      run: cd Msai-Service && ./gradlew deploy
    - name: study
      run: cd Msai-Service && ls
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: Msai-Service/build/libs/Msai-Service.jar
